### PR TITLE
ALOOP Replaced donation with proper tax receipt

### PR DESCRIPTION
**Pull request by aloopmarin007**

### CODE REVIEW

**Review by ResponsibleStaking — CHANGES_REQUESTED** [review]
Hi!
Both of your transactions are Receipts are showing a order date of 14th of July.
There is no date showing that there is a different payment executed.
Is this a recurring payment?
How can I identify that multiple payments where executed?
Regards!

**Comment by aloopmarin007** [comment]
Yes, this is a recurring payment on my credit card. Receipt comes only one time, after that I received only a confirmation. Another MDP admin asked to update the receipt instead of confirmation. I did it on my second PR. Please check on the right side of the amount, it shows as 'Donation recurring monthly' , screenshot attached on my new PR

**Review by ResponsibleStaking — APPROVED** [review]

**Review by ResponsibleStaking — APPROVED** [review]

**Comment by aloopmarin007** [comment]
ALOOP September Donation

**Comment by aloopmarin007** [comment]
Updated Donation for September

**Comment by aloopmarin007** [comment]
I'll create a new PR

**Pull request closed without merging**
