### PR TITLE
Add BELGA donation

### PR DESCRIPTION
**Pull request by way2many**
We are located in Europe so I changed "usd" to "eur" as I have no idea what was the change rate on the day of donation.

### CODE REVIEW

**Comment by way2many** [comment]
Seems that usd is required so changed eur to usd

**Review by kiriakos — APPROVED** [review]
LGTM

**Comment by kiriakos** [comment]
Hi there! Good stuff! I see you worked out the eur/usd stuff already, well done. Do you think this should be better documented?

**Comment by way2many** [comment]
> Hi there! Good stuff! I see you worked out the eur/usd stuff already, well done. Do you think this should be better documented?

I think this should be documented. I understand the need to have a single currency to make a total donation calculation.

**Pull request merged**
