### PR TITLE
DEN Update

### PR DESCRIPTION
**Pull request by DenDev-247**
OK, trying again...

### CODE REVIEW

**Comment by DenDev-247** [comment]
Can somebody please check my donations.yml file ... I've been over with a fine tooth comb and cannot find any conflicts when comparing to other files. The file check fails with a 'SyntaxErrorUnexpected end of JSON input' .... please help, pulling my hair out!

**Comment by aloopmarin007** [comment]
Looks like double quotes on line 62 next to phone nr 
duplicated mapping key (62:5)

 59 |     name: Perth Childrens Hospital  ...
 60 |     address: PO Box 8249, Subiaco E ...
 61 |     tel: +61864562222
 62 |     tel: "+62 (08) 6456 2222"
----------^
 63 |     contact: info@pchf.org.au
 64 |   ada: 34.00

**Comment by aloopmarin007** [comment]
also you have the phone nr twice

**Comment by DenDev-247** [comment]
Still no joy :(

SyntaxErrorUnexpected end of JSON input ???

**Review by aloopmarin007 — APPROVED** [review]
removed spaces on line 93

**Comment by aloopmarin007** [comment]
can you try it one more time?

**Comment by DenDev-247** [comment]
Deleted and re-created donation.yml .... pushing from desktop app, all files present. Still getting SyntaxErrorUnexpected end of JSON input. I'm at a loss ...

**Comment by aloopmarin007** [comment]
Go here https://yamlchecker.com/ and check your raw code. I did and it seems to have 2 more spaces on line 85 that's messing up your indentation

**Comment by DenDev-247** [comment]
Success!

**Pull request merged**
