### PR TITLE
ALOOP changed folder name and update donations

### PR DESCRIPTION
**Pull request by aloopmarin007**
Added donation for 2021-08-14

### CODE REVIEW

**Comment by kiriakos** [comment]
Hi there! Two things:
1. The PR only has an image file added, you probably also want to add the donation to your `donations.yml`
2. Your ticker folder is `ALoop` which technically is ok but we definitely prefer having tickers in ALLCAPS so that they keep being easily identifyable. can you change that?

**Comment by aloopmarin007** [comment]
Hello,
Changed ticker to upper case and updated donations.yml

**Comment by aloopmarin007** [comment]
Changed ticker to upper case and updated donations.yml

**Comment by kiriakos** [comment]
Hey, thanks for implementing the changes.

FYI, the file `ALOOP/2021-08-14-ABG.png` is a bit thin on details, it has neither a name nor a date in it. Usually we expect a name (or email), a date and the donation amount to be on the uploaded documents. Please keep this in mind for the next time.

**Review by kiriakos — APPROVED** [review]
LGTM, please make sure proofs contain a name (or email), a date and the value donated in the future.

**Pull request merged**
