### PR TITLE
Added March donations for IPIB

### PR DESCRIPTION
**Pull request by sirluke79**

### CODE REVIEW

**Comment by ResponsibleStaking** [comment]
There is some issue with the structure of the YML File. Please check Check #1 below

#1 Yaml Structure fitting the example: :no_entry: (Invalid characters before values of announcement_url, April donation does not contain recipient details)
Current: 
  announcement_url: &ann https://www.italianspib.it/the-giveaway
  recipient: &stc
    name: Save the Children ITALIA ONLUS
    ...
Should:
  announcement_url: https://www.italianspib.it/the-giveaway
  recipient:
    name: Save the Children ITALIA ONLUS
    ...
#2 Recipient is a valid organization: :white_check_mark:
#3 ADA / USD Conversin rate: :white_check_mark:
#4 Timestamp is valid: :white_check_mark:, 7.03.2021 (acutal transferdaate 8.3.2021, 30€) and 2.04.2021 (actual transfer date is 7.4.2021, 50€)
#5 Linked files are existant: :white_check_mark:
#6 Receipt Total amount matches mentioned amount: :white_check_mark:
#7 Receipt shows address of Donation recipient: :white_check_mark:  (Recipient IBAN is assigned to the correct organization)
#8 Receipt shows Date of the donation and matches timestamp in YML: :white_check_mark:  (not exact match of the date but close to it)

**Comment by sirluke79** [comment]
> There is some issue with the structure of the YML File. Please check Check #1 below
> 
> #1 Yaml Structure fitting the example: ✅
> #2 Recipient is a valid organization: ✅
> #3 ADA / USD Conversin rate: ✅
> #4 Timestamp is valid: ✅, 7.03.2021 (acutal transferdaate 8.3.2021, 30€) and 2.04.2021 (actual transfer date is 7.4.2021, 50€)
> #5 Linked files are existant: ✅
> #6 Receipt Total amount matches mentioned amount: ✅
> #7 Receipt shows address of Donation recipient: ✅ (Recipient IBAN is assigned to the correct organization)
> #8 Receipt shows Date of the donation and matches timestamp in YML: ✅ (not exact match of the date but close to it)

I'm sorry but I don't see where the yml is not fitting the structure. I added the second sentry on previous one that was ok.

**Comment by ResponsibleStaking** [comment]
Sorry, the comment was updated. All checks were OK.
PR is just waiting for an Admin to get merged.

**Review by way2many — APPROVED** [review]
Looks good.

**Pull request merged**
