### PR TITLE
New ticket - added previous donations

### PR DESCRIPTION
**Pull request by steveaggie**

### CODE REVIEW

**Review by ResponsibleStaking — CHANGES_REQUESTED** [review]
Please also add the Receipt so we can verify the recipient and sender of the donation.

**Comment by steveaggie** [comment]
The receipt is this file:  Delete Oasis Giving thru August 2021.png

**Comment by ResponsibleStaking** [comment]
> The receipt is this file: Delete Oasis Giving thru August 2021.png

This looks like an overview page. I see a link which lets you download the receipt from there. I hoped that the receipt includes proper origin and reciepient information.

**Comment by steveaggie** [comment]
Ok, I think I've got what you're looking for now.  It's the latest receipt.  I hope I'm doing the github stuff correctly.

**Review by ResponsibleStaking — APPROVED** [review]

**Pull request merged**
