### PR TITLE
Second CPU donation

### PR DESCRIPTION
**Pull request by filip-strelec**
This PR adds the second donation for CPU pool

### CODE REVIEW

**Comment by ResponsibleStaking** [comment]
Looks all good. Please add the Transaction ID in your next Donation in the optional attribute charity_tx_id

**Review by ResponsibleStaking — APPROVED** [review]

**Comment by ResponsibleStaking** [comment]
Unfortunately i cannot merge because the branch is out of date with the base branch.
Hope this link helps you to get this sorted: https://stackoverflow.com/questions/53712930/how-to-fix-this-in-git-this-branch-is-out-of-date-with-the-base-branch

**Comment by filip-strelec** [comment]
> 
> 
> Unfortunately i cannot merge because the branch is out of date with the base branch.
> Hope this link helps you to get this sorted: https://stackoverflow.com/questions/53712930/how-to-fix-this-in-git-this-branch-is-out-of-date-with-the-base-branch

Should be good now... :)

**Comment by kiriakos** [comment]
Since @ResponsibleStaking  already had greenlighted the content I went ahead and merged this one.

**Pull request merged**
