### PR TITLE
Update [SAPIO] Donations

### PR DESCRIPTION
**Pull request by adacapo21**
Update [SAPIO] Donations

added further donations to **FLOGA and Mediteranean Saving Humans** from SAPIO community

### CODE REVIEW

**Comment by nova4005** [comment]
Why is this commit pushing donations.json files into other pools folders. I think you will need to remove those and push up to your pools folder.

**Comment by adacapo21** [comment]
> Why is this commit pushing donations.json files into other pools folders? I think you will need to remove those and push up to your pools folder.

I wasn't aware of it before your comment here. Maybe it happened, when I updated my current branch with the upstream repository. I followed this link [here ](https://github.com/CardanoMDP/Donations#keeping-your-repository-up-to-date-with-the-upstream-repository-cardanomdpdonations)from README. 

To confirm should I delete all these json from my PR? Should I add a donations.json or is added automatically? 
Also, I want to add some things in my donations.yml which are necessary, too. 
I'm waiting your guidance about it.

Thanks 
Aggelos

**Comment by nova4005** [comment]
Hey, sorry for the delay. Yes you need to remove the json files from the pull request. The automated checks will look at your YAML file to make sure it passes so you should not need to have a json file in your folder either, unless you wanted to parse it for other purposes.

**Comment by adacapo21** [comment]
PR Updated as Garett suggested! Please let me know if any other change is needed. Thanks

**Comment by nova4005** [comment]
Thanks for removing those files. I didn't see this until this morning but you have two entries for the Social Hackers Academy on the same day in the donations.yml file. Are those two separate payments or are they the same? If they are they same we would just want one entry for them in the YAML file.

**Review by nova4005 — APPROVED** [review]
LGTM

**Pull request merged**
