### PR TITLE
DEN donations update #2

### PR DESCRIPTION
**Pull request by DenDev-247**
Ok, I've had a look and I think i found the problem? Please try again

### CODE REVIEW

**Review by aloopmarin007 — APPROVED** [review]
LGT

**Comment by aloopmarin007** [comment]
Still fails

**Comment by DenDev-247** [comment]
Any ideas? I'm really stumped here... I've looked at others' and my format seems to be the same, nothing really changed from previous pull requests...

**Comment by aloopmarin007** [comment]
> Any ideas? I'm really stumped here... I've looked at others' and my format seems to be the same, nothing really changed from previous pull requests...

Not sure, if you did a branch update before, but something must be in conflict with main branch, I gad the same issue at some point, and I tried to delete and re-create donations.yml, delete PRs and issue a new ones. None of them worked. 
In the end I had to install Github desktop and pushed my PR request from desktop app and issue was fixed without touching anything in donations'yml

**Comment by DenDev-247** [comment]
Think its ok now?

**Pull request closed without merging**
