### PR TITLE
PSYA July donations update

### PR DESCRIPTION
**Pull request by rafek47**

### CODE REVIEW

**Comment by kiriakos** [comment]
@rafek47 Somethig isn't rigt with this PR. It shows me as if all three donations are new and the files associated with the first donations are marked new as well even though they have not chaged. Can you maybe take a look on you side? Could be that you just need to sync your Fork with `CardanoMDP/Donations`

**Comment by rafek47** [comment]
> @rafek47 Somethig isn't rigt with this PR. It shows me as if all three donations are new and the files associated with the first donations are marked new as well even though they have not chaged. Can you maybe take a look on you side? Could be that you just need to sync your Fork with `CardanoMDP/Donations`

Thanks for feedback, not sure why is it like that. I've seen it too. Will try again.

**Comment by kiriakos** [comment]
Maybe try this one:
https://github.com/CardanoMDP/Donations/pull/129

**Comment by kiriakos** [comment]
@rafek47 the file `PSYA/julyOneTreePlanted.jpg` seems to be missing in the PR. It is mentioned in `donations.yml` but doesn't exist as a file here

**Comment by rafek47** [comment]
> @rafek47 the file `PSYA/julyOneTreePlanted.jpg` seems to be missing in the PR. It is mentioned in `donations.yml` but doesn't exist as a file here

Sorry about that, just added. 
Thank you so much

**Review by kiriakos — APPROVED** [review]

**Pull request merged**
