### PR TITLE
PSYA donations October

### PR DESCRIPTION
**Pull request by rafek47**

### CODE REVIEW

**Comment by nova4005** [comment]
Some of the donations are missing the files for them, if you can update those I can get this merged in for you.

**Comment by rafek47** [comment]
> Some of the donations are missing the files for them, if you can update those I can get this merged in for you.

Hi, is it necessary to provide screenshots if the last 2 donations are in ADA and are easily trackable by the txIDs?

**Comment by nova4005** [comment]
I did see that and it does make sense, but the automated checks fail which is blocking the merge. We may be able to update the workflow but I will have to get with Brian for that.

**Comment by rafek47** [comment]
No worries, I will provide them very soon. Thanks for the reply.

**Comment by rafek47** [comment]
All should be good now. Thank you for your work on this repository :)

**Review by nova4005 — APPROVED** [review]
LGTM

**Pull request merged**
