### PR TITLE
Add donations #33820 and  #34157

### PR DESCRIPTION
**Pull request by CardenPool**

### CODE REVIEW

**Comment by CardenPool** [comment]
Please, add this donations. To honor the CF whale, we're starting some mkt initiatives and we want to talk about MDP alliance and how the donations are tracked. Have a great day, Antonello

**Comment by BrianLee12** [comment]
Hey There CardenPool, it looks like there are some issues with your provided information:

Timestamp on first donation incorrect:  1632199797 = Tue Sep 21 2021

tel = telephone , not email. You can make an email field to add an email address. Email address doesn't match contact info on receipt or on website - please supply matching info.

Address seems to be incorrect 23 - 20121 Milano on receipts instead of 16 - 20121 Milano.

Please make changes so that we can proceed further, thank you!

**Comment by CardenPool** [comment]
> Hey There CardenPool, it looks like there are some issues with your provided information:
> 
> Timestamp on first donation incorrect: 1632199797 = Tue Sep 21 2021
> 
> tel = telephone , not email. You can make an email field to add an email address. Email address doesn't match contact info on receipt or on website - please supply matching info.
> 
> Address seems to be incorrect 23 - 20121 Milano on receipts instead of 16 - 20121 Milano.
> 
> Please make changes so that we can proceed further, thank you!

GM Brian. Thanks for your review. I made some mess with the address of the intermediate company and the epoch date converter. All the fields were updated. I took the opportunity do add some custom fields. Hope everything is fine now. Have a good day, Antonello

**Comment by nova4005** [comment]
Hey, I found some issues with the donations.yml file. If you copy it into http://www.yamllint.com/ you will be able to fix the formatting. I also fixed the formatting in this pull request if you want to copy it there.

The ADA amount needs to be converted to USD and not EUR.

For the files they should have your folder name at the beginning, so in your case it would be.

CRPL/Certificazione_Fiscale_20210910_307840.png

Let me know if you have any questions.

**Comment by CardenPool** [comment]
> Hey, I found some issues with the donations.yml file. If you copy it into http://www.yamllint.com/ you will be able to fix the formatting. I also fixed the formatting in this pull request if you want to copy it there.
> 
> The ADA amount needs to be converted to USD and not EUR.
> 
> For the files they should have your folder name at the beginning, so in your case it would be.
> 
> CRPL/Certificazione_Fiscale_20210910_307840.png
> 
> Let me know if you have any questions.

Thanks for your feedback. I've updated the file following your suggestions. Hope everything is fine now. Have a good day.

**Review by nova4005 — APPROVED** [review]
LGTM

**Pull request merged**
