### PR TITLE
4 more donations! 

### PR DESCRIPTION
**Pull request by StakeWithPride**

### CODE REVIEW

**Comment by kiriakos** [comment]
@StakeWithPride any idea why the whole donations yml gets marked as a conflict?

**Comment by StakeWithPride** [comment]
> 
> 
> @StakeWithPride any idea why the whole donations yml gets marked as a conflict?

Where do you see this conflict? I've followed the same process as in the past (I think). I reviewed the content of the yml and it looks okay. Perhaps if you can point me to the error message I can google and reverse engineer what went wrong. I do notice those new token errors all the way back in April, not sure if related. Will re-review my steps in the mean time.

**Comment by kiriakos** [comment]
Well... exactly here :-D

If I click on resolve conflicst it marks your whole donations.yml file as conflicting.

image

**Comment by kiriakos** [comment]
Okay, I sorted it out. for some reason the empty ending lines of the file made git throw up.

**Comment by StakeWithPride** [comment]
> 
> 
> Okay, I sorted it out. for some reason the empty ending lines of the file made git throw up.

TIL! Okay will look out for that next time. Thanks for being the Github hero.

**Review by kiriakos — APPROVED** [review]
LGTM

**Pull request merged**
