### PR TITLE
CPU's 6th charity donation

### PR DESCRIPTION
**Pull request by filip-strelec**
Our 6th charity donation

### CODE REVIEW

**Comment by filip-strelec** [comment]
CPU made it's 7th donation, it's also in this PR

**Comment by kiriakos** [comment]
@filip-strelec Your PRs contents seem fine. Unfortunately github cannot merge this PR automatically and we have disabled direct pushing to the repo. This usually happens when Somebody other than you had to fix a PR file in a previous commit (for example to correct indentation). Can you update your fork of the `Donations` repo locally and push it to your account? This would resolve the github problem and allow me to complete this PR

**Comment by kiriakos** [comment]
Please check #129 for how to resolve this.

**Comment by filip-strelec** [comment]
Should be ok now :)

**Review by kiriakos — APPROVED** [review]

**Comment by kiriakos** [comment]
@filip-strelec can you add a short tutorial on how to keep your fork up to date and add it to this repo's readme? First the github way and then the cli way (afaik, the github way doesn't always work)

**Comment by filip-strelec** [comment]
> @filip-strelec can you add a short tutorial on how to keep your fork up to date and add it to this repo's readme? First the github way and then the cli way (afaik, the github way doesn't always work)

Sure, will do in upcoming days

**Pull request merged**
