### PR TITLE
donations.yml

### PR DESCRIPTION
**Pull request by hubthom**

### CODE REVIEW

**Review by kiriakos — CHANGES_REQUESTED** [review]

**Comment by kiriakos** [comment]
@hubthom sorry for the wait, aparently I started the review but never send it out...

**Comment by aloopmarin007** [comment]
Any info if we keep going with this PR or close it?

**Comment by hubthom** [comment]
Can you please reminds me what is this PR?

 

Thank you thomas

 

From: ResponsibleStaking ***@***.***>
Reply to: CardanoMDP/Donations ***@***.***>
Date: Thursday, 14. October 2021 at 8:07 AM
To: CardanoMDP/Donations ***@***.***>
Cc: Thomas Tsipoulanis ***@***.***>, Mention ***@***.***>
Subject: Re: [CardanoMDP/Donations] donations.yml (#59)

 

@hubthom ! Are you still want to continue with this PR or can we delete it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aloopmarin007** [comment]
Hey, it was to update your donations.yml as per Kiriakos with "ada and usd values. Can you please calculate those based on the Feb 10 2021 exachnge rates and update this file?"  or we can close the PR.

**Comment by aloopmarin007** [comment]
Please read the comments on GitHub for your PR. We need to solve this PR, either close it or resolve the errors.
Can be found here https://github.com/CardanoMDP/Donations/pull/59
Thank you,

**Comment by aloopmarin007** [comment]
I think we can close this PR, been a full year, since no updates

**Pull request closed without merging**
