### PR TITLE
Donation Updates thru end of 2021

### PR DESCRIPTION
**Pull request by HungryWookie**
Hey Guys,
Cleaned up my Donation receipts and donation file.  Please check it when you get a chance.  With the backup, I don't think RADAR has ever been formally included on the MDP folder list.  Please merge or let me know if there are problems!

### CODE REVIEW

**Comment by HungryWookie** [comment]
I think I fixed my donations.yml file?  Please review when you have a sec!

**Review by aloopmarin007 — APPROVED** [review]

**Comment by aloopmarin007** [comment]
Can't tell what's wrong. but it fails validation

**Comment by HungryWookie** [comment]
OK, That merge got a lot farther.  I now have changed my documentation pdf file names to take out spaces....  Hopefully we're close.  Thanks for this sticking with me...

**Comment by aloopmarin007** [comment]
All good, merged

**Pull request merged**
