### PR TITLE
5th donation for SVRN // Sleeping Natives

### PR DESCRIPTION
**Pull request by sleepingnatives**

### CODE REVIEW

**Comment by kiriakos** [comment]
@sleepingnatives can you merge the current HEAD of `CardanoMDP/Donations` `master` branch and push it to your fork? You might get a merge conflict due to a change we did in your last PR iirc. Github doesn't allow me to merge this due to diverging histories.

**Comment by sleepingnatives** [comment]
@kiriakos branch updated successfully just now - merge okay?

**Comment by kiriakos** [comment]
image
It still isn't giving me a chance....
can you please confirm that you did the following?

```
git clone git@github.com:CardanoMDP/Donations.git
cd Donations
git remote add svrn https://github.com/Sleeping-Natives-Productions/Donations.git

git fetch --all
git merge svrn/main
git push svrn main
```

I checked (via my own fork) and these instructions allow me to merge this. See #129 for what I exactly did

**Comment by sleepingnatives** [comment]
Re-forked after deleting old one and will re-submit afresh.

**Pull request closed without merging**
