### PR TITLE
AMOON NOV 2022 Donation to Save The Children Epoch 371 -376

### PR DESCRIPTION
**Pull request by adamoonpool**
Pls review and approve the PR. Thanks.

### CODE REVIEW

**Review by aloopmarin007 — APPROVED** [review]
LGTM

**Comment by aloopmarin007** [comment]
Hey AMOON, can you solve the conflicts on your branch, so we can merge it. Thanks.

**Comment by adamoonpool** [comment]
Hello ALOOP, I fixed the .yml file and added current month donation too. Pls let me know for any issues. Thank you.        Merry Christmas & Happy New Year!

**Comment by aloopmarin007** [comment]
@kiriakos maybe Kiriakos can help with this, but it still fails. I would love to help, but I don't know about this error.

**Review by nova4005 — APPROVED** [review]
the two ticker lines for newest commits had two extra spaces in the beginning. I removed those and everything else looks good.

**Pull request merged**
