### PR TITLE
SVRN_3-22-21

### PR DESCRIPTION
**Pull request by sleepingnatives**

### CODE REVIEW

**Comment by kiriakos** [comment]
Hi there @sleepingnatives, I'm going over your Donation receipts and a couple things are not completely clear to me.

1. You say you have donated but also show that you increased your pledge with that amount. Typically that would not be considered a donation as all SPOs increase their pledge amount from their rewards.
2. What exactly is Sleeping Natives Productions doing with these funds? Will they be used to film (the 2min video)[https://sleepingnatives.org/thefilm.html]?  When will that happen? Is there some sort of progress tracking for the funding target?

**Comment by sleepingnatives** [comment]
Hi Kiriakos,

 

Thank you for your email. We are not a typical “Charity Pool”. Most so-called “Charity Pools” are not charities at all, but instead donate a percentage of their rewards to an actual, registered charity/non-profit. We, on the other hand, ARE an actual registered non-profit organization, and our focus is on supporting alternative energy technology inventors against their already well-entrenched counterparts in the fossil-fuel, nuclear, coal, and automotive industries. If you have a look at our non-profit’s website (both the home page <https://sleepingnatives.org/index.html> , and our projects page <https://sleepingnatives.org/projects.html> ), you’ll see we devote our efforts to environmental educational projects, both for the purpose of drawing attention to this subject, as well as for a feature-length documentary delving into the issues in greater detail.

 

I had this conversation with Brian already so I am copying him on this email. Please let me know if there’s any other questions or concerns you may have?

 

Our pledge wallet is the means by which donations made to our non-profit are both collected and can be tracked. We are committed to donating a minimum of 80% of our stake pool’s rewards back into our pledge for the purpose of these projects.

 

Many thanks for your time in this! 😊

 

Best regards,

Philip de Souza

Sleeping Natives | SVRN

**Comment by sleepingnatives** [comment]
Recommended changes applied for announcement_url (now https://sleepingnatives.org/donations.html). Both websites adjusted to take visitors to dedicated Donations page, from the stake pool's site (here: https://commerce.sleepingnatives.org/#svrn), and from our main site, both from the 'Get Involved' page, within the 'How to help' section (here: https://sleepingnatives.org/joinus.html), and also from our blog page (second entry, here: https://sleepingnatives.org/blog.html). Additional recommendations for greater clarity on budgets for both projects applied within the closing statements of the Donations page itself.

**Review by kiriakos — APPROVED** [review]
Based on the discussion on [CardanoMDP Donations Chat](https://discord.com/channels/821088538538803230/821826106168574023) and @BrianLee12's approval I can also approve this.

**Pull request merged**
