### PR TITLE
2 more donations

### PR DESCRIPTION
**Pull request by seal-pool**

### CODE REVIEW

**Comment by seal-pool** [comment]
note the second payment screenshot is in czech language, as it was donated to zoo in Czechia

**Comment by ResponsibleStaking** [comment]
Reviewed the 2 donations. The one for the Seal Adoption is all fine. For the other the Screenshot of the payment is not including a date. Also it would be great if the receipt somehow shows the adress or name of the Zoo.

Full Details of the review.
#1 Yaml Structure fitting the example: :white_check_mark: 
#2 Recipient is a valid organization: :white_check_mark:
#3 ADA / USD Conversin rate: :white_check_mark:
#4 Timestamp is valid: :white_check_mark:, 27.03.2021
#5 Linked files are existant: :white_check_mark:
#6 Receipt Total amount matches mentioned amount: :white_check_mark:
#6 Receipt shows Pool name: :white_check_mark: (pool name is in, billing address is blacked out)
#7 Receipt shows address of Donation recipient: :no_entry:  (payment4.png is not showing the recepient details)
#8 Receipt shows Date of the donation and matches timestamp in YML: :no_entry: (payment4 does not show a date)

**Comment by seal-pool** [comment]
well, this is how they send the e-mail to us, I zoomed it out so that the address is visible, and also added header from our e-mail client which shows some timestamp, I could maybe also add screenshot of bank transfer, but I would probably need to redact lot of data from there as well, for privacy reasons

**Comment by way2many** [comment]
Our donation proof is a bank statement with redacted info so that would be fine.

**Comment by seal-pool** [comment]
hello, that second version of screenshot already contains all these required information, so I am not sure what is it waiting for, they also already sent us a certificate, I am about to add it too

**Comment by seal-pool** [comment]
we'd like to have this merged so that we can create a new merge request with more documents for next epoch :)

**Review by kiriakos — APPROVED** [review]
LGTM

**Pull request merged**
